cyanray/mirai-cpp

- .gitignore
- examples/CompareMessage.cpp
- examples/FetchEventsViaHTTP.cpp
- include/mirai_bot.hpp
- src/mirai_bot.cpp
重构 mirai_bot.hpp 和 mirai_bot.cpp 并添加注释
> 重构 mirai_bot.hpp 和 mirai_bot.cpp 并添加注释

- src/mirai_bot.cpp
> 修复mirai重启导致异常崩溃的问题

- include/defs/qq_types.hpp
> 去除不推荐的字面量后缀，增强QQ_t和GID_t的易用性

- include/defs/group_config.hpp
- include/defs/message_chain.hpp
- include/defs/messages/AppMessage.hpp
- include/defs/messages/AtAllMessage.hpp
- include/defs/messages/AtMessage.hpp
- include/defs/messages/FaceMessage.hpp
- include/defs/messages/ImageMessage.hpp
- include/defs/messages/JsonMessage.hpp
- include/defs/messages/PlainMessage.hpp
- include/defs/messages/PokeMessage.hpp
- include/defs/messages/QuoteMessage.hpp
- include/defs/messages/XmlMessage.hpp
> 修改文件编码为UTF-8;

- examples/BotEvents.cpp
- include/mirai/defs/group.hpp
> 修复: Group_t 对象 json解析不对称

- examples/RepeatMessage.cpp
- include/mirai/mirai_bot.hpp
- src/mirai_bot.cpp
更新版本号为 1.8.4 (#60)
1. 移除GetRequiredApiVersionInt方法;
1. GetRequiredApiVersion更名为GetMiraiCppVersion;
2. GetApiVersion更名为GetMiraiApiHttpVersion;
1. 更新 examples/RepeatMessage.cpp;
> Release 1.8.4;

- include/mirai/mirai_bot.hpp
> Release 1.9.6;

- include/mirai/mirai_bot.hpp
> Release 1.9.7;

- include/mirai/third-party/WebSocketClient.cpp
- include/mirai/third-party/WebSocketClient.h
- src/mirai_bot.cpp
> BUG修复：高CPU占用 & 事件处理不及时

- CMakeLists.txt
> 修复在mingw下的编译错误(链接winsock)

- include/mirai/third-party/ThreadPool.h
更新: ThreadPool.h 以支持 C++20
Closes #66
> 更新: ThreadPool.h 以支持 C++20

- include/mirai/third-party/WebSocketClient.cpp
> 修复: 潜在的 Segmentation fault.

- include/mirai/third-party/nlohmann/json.hpp
> 更新: 更新 nlohmann/json 为最新版.

- include/mirai/defs/message_chain.hpp
- src/message_chain.cpp
Reverts cyanray/mirai-cpp#80
意义不大，还是revert。
> Revert "提升 MessageChain 的易用性."

- include/mirai/defs/messages/ImageMessage.hpp
- include/mirai/defs/qq_types.hpp
- include/mirai/mirai_bot.hpp
- src/mirai_bot.cpp
> 重构上传图片、语音相关代码.

- include/mirai/mirai_bot.hpp
- src/mirai_bot.cpp
> 新增: 支持设置群聊精华消息.

- include/mirai/defs/defs.hpp
- include/mirai/defs/group_file.hpp
- include/mirai/defs/group_file_info.hpp
- include/mirai/mirai_bot.hpp
- src/mirai_bot.cpp
> 支持获取群文件列表和群文件详细信息.

- include/mirai/mirai_bot.hpp
- src/mirai_bot.cpp
> 新增: 支持群文件相关操作(重命名、移动、删除).

- include/mirai/defs/qq_types.hpp
- include/mirai/mirai_bot.hpp
> 让UID_t、QQ_t、GID_t支持map、unordered_map容器。

- examples/BotEvents.cpp
- examples/Command.cpp
- examples/FetchEventsViaHTTP.cpp
- examples/FileMessage.cpp
- examples/GetFriendList.cpp
- examples/GetGroupList.cpp
- examples/GroupConfig.cpp
- examples/GroupMemberInfo.cpp
- examples/GroupNameChange.cpp
- examples/MemberCardChange.cpp
- examples/MemberJoinEvent.cpp
- examples/MemberLeaveEvent.cpp
- examples/MessageType.cpp
- examples/Mute.cpp
- examples/NewFriendEvent.cpp
- examples/NudgeEvent.cpp
- examples/Recall.cpp
- examples/RecallEvent.cpp
- examples/RepeatMessage.cpp
- examples/RichMessage.cpp
- examples/SendImageMessage.cpp
- examples/VoiceMessage.cpp
- include/mirai/mirai_bot.hpp
- src/mirai_bot.cpp
> 适配 mirai-api-http v2.0.0 (的一部分)

- include/mirai/events/FriendInputStatusChangedEvent.hpp
- include/mirai/events/FriendNickChangedEvent.hpp
- include/mirai/events/GroupAllowAnonymousChatEvent.hpp
- include/mirai/events/GroupAllowConfessTalkEvent.hpp
- include/mirai/events/GroupAllowMemberInviteEvent.hpp
- include/mirai/events/GroupEntranceAnnouncementChangeEvent.hpp
- include/mirai/events/MemberSpecialTitleChangeEvent.hpp
- include/mirai/events/events.hpp
- include/mirai/events/mirai_event.hpp
> 支持 mirai-api-http v2.0.0 的一些新事件

- doc/Documentation.md
- examples/RepeatMessage.cpp
- include/mirai/mirai_bot.hpp
- src/mirai_bot.cpp
> 支持 Reconnect 方法.

- include/mirai/defs/qq_types.hpp
- include/mirai/messages/VoiceMessage.hpp
> 初始化 MiraiVoice, VoiceMessage 的 Length 字段.

- include/mirai/third-party/httplib.h
- src/mirai_bot.cpp
> 更新 cpp-httplib 为最新版

- doc/Documentation.md
- include/mirai/MiraiBot.hpp
- src/EventHelperFunctions.cpp
- src/MiraiBot.cpp
> Fix The Recall Function

- doc/Documentation.md
- include/mirai/MiraiBot.hpp
- src/MiraiBot.cpp
> 添加使用图片URL上传图片的功能

- src/MiraiBot.cpp
> 修改群文件上传接口为正确的URL。
